### ISSUE TITLE
자신이 한 기여 목록 WIKI에 작성

### ISSUE THREAD

**Issue by ghost** [19-1-skku-oss/2019-1-OSS-L3#19]
@19-1-skku-oss/2019-1-oss-l3 

[여기](https://github.com/19-1-skku-oss/2019-1-OSS-L3/wiki/%EA%B8%B0%EC%97%AC-%EB%AA%A9%EB%A1%9D)에 작성해 주시길 바랍니다.

지금까지의 기여목록을 정리하여 발표 때 활용하기 위함입니다.

**Comment by rotmdwo** [comment]
네 알겠습니다.

**Comment by ghost** [comment]
모두 작성했으니 닫겠습니다. 이 이슈와는 상관없이 더 적으실 내용이 있다면 추가하셔도 됩니다.
