### ISSUE TITLE
gh-pages 수정 및 글 작성

### ISSUE THREAD

**Issue by ghost** [19-1-skku-oss/2019-1-OSS-L3#2]
활동 내용 및 프로젝트 소개가 아직 미흡합니다.

자신이 활동한 내용과, 지금까지 쓴 글을 정리하여
[홈페이지](https://19-1-skku-oss.github.io/2019-1-OSS-L3/)에 글을 작성해 주시면 감사하겠습니다

**Comment by ghost** [comment]
https://proud-alligator.cloudvent.net/ 테마 교체

**Comment by minjae1025** [comment]
@19-1-skku-oss/2019-1-oss-l3 

팀원 정보에 오류가 있다고 합니다
https://19-1-skku-oss.github.io/2019-1-OSS-L3/
https://19-1-skku-oss.github.io/2019-1-OSS-L3/members/

체크하고 완료했다고 적어주세요

**Comment by DropFL** [comment]
[프로젝트 소개글](https://19-1-skku-oss.github.io/2019-1-OSS-L3/2019/05/28/%ED%94%84%EB%A1%9C%EC%A0%9D%ED%8A%B8-%EA%B5%AC%EC%A1%B0/)에 내용을 추가했습니다.

**Comment by ghost** [comment]
충분히 소개글을 작성하였다고 판단됩니다. 이후로도 쓸 내용이 있으면 계속 추가해 주시길 바랍니다.
