### ISSUE TITLE
한글 데이터 추가

### ISSUE THREAD

**Issue by ghost** [19-1-skku-oss/2019-1-OSS-L3#3]
[학습 데이터](https://github.com/19-1-skku-oss/2019-1-OSS-L3/tree/master/chatterbot_corpus)를 
추가할 수 있는 폴더가 레포지트리에 추가되었습니다. 많은 기여 바랍니다

**Comment by ghost** [comment]
실제로 데이터를 확인해 보니, 문법 오류가 상당히 많습니다. 수정 부탁드립니다

**Comment by rotmdwo** [comment]
이 부분에 대해 데이터를 더 늘리겠습니다.

**Comment by ghost** [comment]
세부 사항으로 나눠 이슈를 열었습니다. 닫겠습니다.
