### ISSUE TITLE
health.yml, movie.yml 번역

### ISSUE THREAD

**Issue by ghost** [19-1-skku-oss/2019-1-OSS-L3#34]
[health.yml](https://github.com/19-1-skku-oss/2019-1-OSS-L3/blob/master/chatterbot_corpus/data/korean/health.yml)

[movies.yml](https://github.com/19-1-skku-oss/2019-1-OSS-L3/blob/master/chatterbot_corpus/data/korean/movies.yml)

데이터를 번역할 분이 필요합니다.

**Comment by rotmdwo** [comment]
제가 하겠습니다!

**Comment by rotmdwo** [comment]
번역완료.
