### ISSUE TITLE
psychology.yml 번역

### ISSUE THREAD

**Issue by ghost** [19-1-skku-oss/2019-1-OSS-L3#35]
[psychology.yml 데이터를 번역할 분이 필요합니다.](https://github.com/19-1-skku-oss/2019-1-OSS-L3/blob/master/chatterbot_corpus/data/korean/psychology.yml)

양이 많으니 나눠서 하셔도 됩니다.

**Comment by snowdolf99** [comment]
번역 시작하겠습니다..
다 해도 될 것 같아요

**Comment by ghost** [comment]
https://github.com/19-1-skku-oss/2019-1-OSS-L3/pull/42
