### ISSUE TITLE
science.yml 번역

### ISSUE THREAD

**Issue by ghost** [19-1-skku-oss/2019-1-OSS-L3#36]
[이 데이터](https://github.com/19-1-skku-oss/2019-1-OSS-L3/blob/master/chatterbot_corpus/data/korean/science.yml)를 번역할 분이 필요합니다.

**Comment by q-san-g** [comment]
제가 번역하겠습니다

**Comment by ghost** [comment]
https://github.com/19-1-skku-oss/2019-1-OSS-L3/pull/46
