### ISSUE TITLE
money.yml 번역

### ISSUE THREAD

**Issue by ghost** [19-1-skku-oss/2019-1-OSS-L3#37]
[이 데이터](https://github.com/19-1-skku-oss/2019-1-OSS-L3/blob/master/chatterbot_corpus/data/korean/money.yml)를 번역할 분이 필요합니다.

**Comment by snowdolf99** [comment]
제가 하겠습니다.

**Comment by ghost** [comment]
https://github.com/19-1-skku-oss/2019-1-OSS-L3/pull/39
