### ISSUE TITLE
답변을 위키피디아에서 찾아오도록 하기

### ISSUE THREAD

**Issue by ghost** [19-1-skku-oss/2019-1-OSS-L3#44]
원 레포지트리의 1742번 이슈를 보고 재밌어보여 가져왔습니다.

빠르게 개발하면 내일 중으로 완성할 수 있을 것 같습니다.
(함수 한두개만 작성하면 되고 위키피디아에는 API가 존재함)

혹시 참여하고 싶으신 분은 토요일 11시까지 코멘트 남겨주세요

**Comment by rotmdwo** [comment]
흥미로워 보입니다!

**Comment by ghost** [comment]
@rotmdwo 
만약 참여하실 것이라면, 영문 위키피디아에서 api.php를 통해 위키피디아의 설명문을 html, 또는 wikipedia 마크다운 형태가 아닌 파싱된 문자열로 가져오는 방법을 알아봐 주셨으면 합니다.

**Comment by DropFL** [comment]
:+1:

**Comment by ghost** [comment]
https://github.com/19-1-skku-oss/2019-1-OSS-L3/tree/wikipedia/chatterbot

코드 작성하여 추가했습니다.

추가적인 commit은 여기로 PR해 주시길 바랍니다.

최종적으로 master branch에 merge하는 것은 월요일날 아침 하겠습니다

**Comment by ghost** [comment]
https://github.com/19-1-skku-oss/2019-1-OSS-L3/pull/49

**Comment by minjae1025** [comment]
https://github.com/19-1-skku-oss/2019-1-OSS-L3/pull/49
